spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      naming:
        physical-stategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/personal_bot
    username: test
    password: 1234

discord:
  token:
    bot: tu-token